modLoader="javafml"
loaderVersion="[${loader_version},)"
license="LGPL-3.0 license"

[[mods]]
modId="beyond_earth"
version="${mod_version}"
displayName="Beyond Earth (Orbita Edit)"
displayURL="https://github.com/janewsome63/BeyondEarth-Orbita"
logoFile="logo.png"
authors="MrScautHD, rennautogirl63"
description='''Fly to Other Planets and Beyond!'''

[[dependencies.beyond_earth]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version}]"
    ordering="NONE"
    side="BOTH"

[[dependencies.beyond_earth]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},]"
    ordering="NONE"
    side="BOTH"