modLoader="javafml"
loaderVersion="[${loader_version},)"
license="LGPL-3.0 license"

[[mods]]
modId="beyond_orbita"
version="${mod_version}"
displayName="Beyond Orbita"
displayURL="https://github.com/janewsome63/Beyond-Orbita/blob/1.18.2/src/main/resources/SOURCES.md"
logoFile="logo.png"
authors="rennautogirl63"
description='''Fork of Beyond Earth modified for the Orbita modpack. Please visit the link above or read the SOURCES.md file inside the .jar for credits and changes from the original.'''

[[dependencies.beyond_orbita]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version}]"
    ordering="NONE"
    side="BOTH"

[[dependencies.beyond_orbita]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},]"
    ordering="NONE"
    side="BOTH"

[[dependencies.beyond_orbita]]
    modId="create"
    mandatory=true
    versionRange="[0.5.0c,]"
    ordering="NONE"
    side="BOTH"

[[dependencies.beyond_orbita]]
    modId="simpleplanes"
    mandatory=true
    versionRange="[1.18.2-4.14.1,]"
    ordering="NONE"
    side="BOTH"