modLoader="javafml"
loaderVersion="[${loader_version},)"
license="LGPL-3.0 license"

[[mods]]
modId="beyond_orbita"
version="${mod_version}"
displayName="Beyond Orbita"
displayURL="https://github.com/janewsome63/Beyond-Orbita"
logoFile="logo.png"
authors="rennautogirl63"
description='''Fork of Beyond Earth modified for the Orbita modpack. Licensed under LGPL-3.0. Please visit the linked repo or the "sources.txt" file inside the .jar for changes from and links to the original source.'''

[[dependencies.beyond_orbita]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version}]"
    ordering="NONE"
    side="BOTH"

[[dependencies.beyond_orbita]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},]"
    ordering="NONE"
    side="BOTH"